<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login Test"
           tests="4"
           failures="2"
           errors="0"
           skipped="0"
           time="5.013">
  <properties />
            <testcase name="verifyThatUserShouldLogOutSuccessFully" time="1.927" classname="com.nopcommerce.demo.testsuite.LoginPageTest">
                <failure type="org.openqa.selenium.StaleElementReferenceException"
                  message="stale element reference: stale element not found
  (Session info: chrome=125.0.6422.176)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: &apos;4.21.0&apos;, revision: &apos;79ed462ef4&apos;
System info: os.name: &apos;Windows 11&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;10.0&apos;, java.version: &apos;17.0.8&apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [fc8d0b75edb7e2e1d1de9704105307f8, getElementText {id=f.000D9D8BB0B2D08F775A14E9914A2089.d.902B33EA18BB86A9D2A68B7770C3D671.e.14}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 125.0.6422.176, chrome: {chromedriverVersion: 125.0.6422.141 (4b1e8393712..., userDataDir: C:\Users\sampa\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:60349}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:60349/devtoo..., se:cdpVersion: 125.0.6422.176, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (fc8d0b75edb7e2e1d1de9704105307f8)] -&gt; xpath: //a[normalize-space()=&apos;Log in&apos;]]
Session ID: fc8d0b75edb7e2e1d1de9704105307f8"
              >
<![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: stale element not found
  (Session info: chrome=125.0.6422.176)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [fc8d0b75edb7e2e1d1de9704105307f8, getElementText {id=f.000D9D8BB0B2D08F775A14E9914A2089.d.902B33EA18BB86A9D2A68B7770C3D671.e.14}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 125.0.6422.176, chrome: {chromedriverVersion: 125.0.6422.141 (4b1e8393712..., userDataDir: C:\Users\sampa\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:60349}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:60349/devtoo..., se:cdpVersion: 125.0.6422.176, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (fc8d0b75edb7e2e1d1de9704105307f8)] -> xpath: //a[normalize-space()='Log in']]
Session ID: fc8d0b75edb7e2e1d1de9704105307f8
  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
  java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
  org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
  org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
  org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
  org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
  org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
  org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
  org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
  org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:191)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
  jdk.proxy2/jdk.proxy2.$Proxy16.getText(Unknown Source)
  com.nopcommerce.demo.utilities.Utility.getTextFromElement(Utility.java:61)
  com.nopcommerce.demo.pages.HomePage.getLoginLinkText(HomePage.java:44)
  com.nopcommerce.demo.testsuite.LoginPageTest.verifyThatUserShouldLogOutSuccessFully(LoginPageTest.java:75)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:739)
  org.testng.TestRunner.run(TestRunner.java:614)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
  org.testng.SuiteRunner.run(SuiteRunner.java:312)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
  org.testng.TestNG.runSuites(TestNG.java:1112)
  org.testng.TestNG.run(TestNG.java:1079)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
      </failure>

          </testcase>
            <testcase name="verifyTheErrorMessageWithInValidCredentials" time="1.066" classname="com.nopcommerce.demo.testsuite.LoginPageTest">
                <failure type="java.lang.AssertionError"
                  message="expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.
The credentials provided are incorrect]"
              >
<![CDATA[java.lang.AssertionError: expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.
The credentials provided are incorrect]
  org.testng.Assert.fail(Assert.java:111)
  org.testng.Assert.failNotEquals(Assert.java:1578)
  org.testng.Assert.assertEqualsImpl(Assert.java:150)
  org.testng.Assert.assertEquals(Assert.java:132)
  org.testng.Assert.assertEquals(Assert.java:656)
  org.testng.Assert.assertEquals(Assert.java:666)
  com.nopcommerce.demo.testsuite.LoginPageTest.verifyTheErrorMessageWithInValidCredentials(LoginPageTest.java:46)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:739)
  org.testng.TestRunner.run(TestRunner.java:614)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
  org.testng.SuiteRunner.run(SuiteRunner.java:312)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
  org.testng.TestNG.runSuites(TestNG.java:1112)
  org.testng.TestNG.run(TestNG.java:1079)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="userShouldNavigateToLoginPageSuccessFully" time="0.612" classname="com.nopcommerce.demo.testsuite.LoginPageTest" />
                <testcase name="verifyThatUserShouldLogInSuccessFullyWithValidCredentials" time="1.408" classname="com.nopcommerce.demo.testsuite.LoginPageTest" />
      
</testsuite>
